test(pipeline): test against Elasticsearch 7 and 8

diff --git a/.github/actions/build-and-run-kuzzle/action.yml b/.github/actions/build-and-run-kuzzle/action.yml
--- a/.github/actions/build-and-run-kuzzle/action.yml
+++ b/.github/actions/build-and-run-kuzzle/action.yml
@@ -24,7 +24,16 @@ runs:
       shell: bash
 
     - run: |
-        trap 'docker compose -f ./.ci/services.yml logs' err
+        if [ "$ES_VERSION" == "7" ]; then
+            YML_FILE='./.ci/services-7.yml'
+        elif [ "$ES_VERSION" == "8" ]; then
+            YML_FILE='./.ci/services-8.yml'
+        else
+            echo "Invalid ES_VERSION. It should be either '7' or '8'."
+            exit 1 
+        fi
+
+        trap 'docker compose -f $YML_FILE logs' err
 
         export MAX_TRIES=60
         ./bin/wait-kuzzle
