test(pipeline): fix issues to pass es version

diff --git a/.github/actions/build-and-run-kuzzle/action.yml b/.github/actions/build-and-run-kuzzle/action.yml
--- a/.github/actions/build-and-run-kuzzle/action.yml
+++ b/.github/actions/build-and-run-kuzzle/action.yml
@@ -2,8 +2,11 @@ name: Build and Run Kuzzle image
 description: Build and Run Kuzzle image
 
 inputs:
-  KUZZLE_IMAGE:
+  kuzzle-image:
     description: Kuzzle image target
+    required: true
+  es-version:
+    description: Elasticsearch version to use
     required: true
 
 runs:
@@ -19,11 +22,25 @@ runs:
       shell: bash
 
     - run: |
-        export KUZZLE_IMAGE=${{ inputs.KUZZLE_IMAGE }}
-        docker compose -f ./.ci/services.yml up -d
+        export KUZZLE_IMAGE=${{ inputs.kuzzle-image }}
+        export ES_VERSION=${{ inputs.es-version }}
+
+        if [ "$ES_VERSION" == "7" ]; then
+            YML_FILE='./.ci/services-7.yml'
+        elif [ "$ES_VERSION" == "8" ]; then
+            YML_FILE='./.ci/services-8.yml'
+        else
+            echo "Invalid ES_VERSION. It should be either '7' or '8'."
+            exit 1 
+        fi
+
+        docker compose -f $YML_FILE up -d
       shell: bash
 
     - run: |
+        export KUZZLE_IMAGE=${{ inputs.KUZZLE_IMAGE }}
+        export ES_VERSION=${{ inputs.es-version }}
+
         if [ "$ES_VERSION" == "7" ]; then
             YML_FILE='./.ci/services-7.yml'
         elif [ "$ES_VERSION" == "8" ]; then
@@ -41,5 +58,18 @@ runs:
         trap - err
       shell: bash
 
-    - run: docker compose -f ./.ci/services.yml down
+    - run: |
+        export KUZZLE_IMAGE=${{ inputs.KUZZLE_IMAGE }}
+        export ES_VERSION=${{ inputs.es-version }}
+
+        if [ "$ES_VERSION" == "7" ]; then
+            YML_FILE='./.ci/services-7.yml'
+        elif [ "$ES_VERSION" == "8" ]; then
+            YML_FILE='./.ci/services-8.yml'
+        else
+            echo "Invalid ES_VERSION. It should be either '7' or '8'."
+            exit 1 
+        fi
+
+        docker compose -f $YML_FILE down -v
       shell: bash
